# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcribeglass.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transcribeglass.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15transcribeglass.proto\x12\x0ftranscribeglass\"\x83\x01\n\rClientMessage\x12\x36\n\rselect_source\x18\x01 \x01(\x0b\x32\x1d.transcribeglass.SelectSourceH\x00\x12/\n\theartbeat\x18\x02 \x01(\x0b\x32\x1a.transcribeglass.HeartbeatH\x00\x42\t\n\x07payload\"!\n\x0cSelectSource\x12\x11\n\tsource_id\x18\x01 \x01(\x05\"\x1e\n\tHeartbeat\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x7f\n\rServerMessage\x12\x31\n\ntranscript\x18\x01 \x01(\x0b\x32\x1b.transcribeglass.TranscriptH\x00\x12\x30\n\x07sources\x18\x02 \x01(\x0b\x32\x1d.transcribeglass.SourceUpdateH\x00\x42\t\n\x07payload\"-\n\nTranscript\x12\x11\n\tsource_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"8\n\x0cSourceUpdate\x12(\n\x07sources\x18\x01 \x03(\x0b\x32\x17.transcribeglass.Source\"K\n\x06Source\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x10\n\x08\x61\x63tivity\x18\x04 \x01(\x02\x12\r\n\x05\x61ngle\x18\x05 \x01(\x02\x32j\n\x0fTranscribeGlass\x12W\n\x11StreamInteraction\x12\x1e.transcribeglass.ClientMessage\x1a\x1e.transcribeglass.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribeglass_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=43
  _globals['_CLIENTMESSAGE']._serialized_end=174
  _globals['_SELECTSOURCE']._serialized_start=176
  _globals['_SELECTSOURCE']._serialized_end=209
  _globals['_HEARTBEAT']._serialized_start=211
  _globals['_HEARTBEAT']._serialized_end=241
  _globals['_SERVERMESSAGE']._serialized_start=243
  _globals['_SERVERMESSAGE']._serialized_end=370
  _globals['_TRANSCRIPT']._serialized_start=372
  _globals['_TRANSCRIPT']._serialized_end=417
  _globals['_SOURCEUPDATE']._serialized_start=419
  _globals['_SOURCEUPDATE']._serialized_end=475
  _globals['_SOURCE']._serialized_start=477
  _globals['_SOURCE']._serialized_end=552
  _globals['_TRANSCRIBEGLASS']._serialized_start=554
  _globals['_TRANSCRIBEGLASS']._serialized_end=660
# @@protoc_insertion_point(module_scope)
